### ISSUE TITLE
custom panel formats via parameter files or similar

### ISSUE THREAD

**Issue by jsleeio** [jsleeio/go-eagle#4]
There are a huge variety of off-the-shelf enclosures available that can accommodate a custom front panel. It would be nice if `schroff` (which really needs a new name!) could support these via files that define their parameters. YAML preferred here, as they're likely to be manually written by humans. Dimensions should be in metric (millimetres). Something like the below (completely made up) example maybe?

```yaml
kind: enclosure
notes:
  manufacturer: 'ACME Enclosures Inc'
  partnumber: 'aenc-100-75-30'
spec:
  width: 100
  height: 75
  cornerRadius: 5
  mountingHoles:
  - { x: 10, y: 10, size: 3 }
  - { x: 90, y: 10, size: 3 }
  - { x: 10, y: 65, size: 3 }
  - { x: 90, y: 65, size: 3 }
```
